[package]
name = "libhttp"
build = "make"
repository = "github.com/briandowns/libhttp"
homepage = ""
version = "0.1.0" 
description = "A collection of useful values to be used with HTTP in C."
authors = ["Brian J. Downs"]

[dependencies]

